Update configure script because RPM didn't build on my system
(Old svn revision: 704)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13492,7 +13492,6 @@ if test "$CC" = "gcc" -o "$CC" = "g++"; then
   fi
 fi
 
-#echo "dbg:target $target"
 case "$target" in
 "")
 ;;
@@ -13549,29 +13548,29 @@ cat >>confdefs.h <<\EOF
 #define REQUIRES_STASHEVENT 1
 EOF
 
-echo "$as_me:13552: checking if prototype for gethostname exists" >&5
+echo "$as_me:13551: checking if prototype for gethostname exists" >&5
 echo $ECHO_N "checking if prototype for gethostname exists... $ECHO_C" >&6
 cat >conftest.$ac_ext <<_ACEOF
-#line 13555 "configure"
+#line 13554 "configure"
 #include "confdefs.h"
 
 #include <unistd.h>
 _ACEOF
 if (eval "$ac_cpp conftest.$ac_ext") 2>&5 |
   egrep "gethostname" >/dev/null 2>&1; then
-  echo "$as_me:13562: result: yes" >&5
+  echo "$as_me:13561: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 cat >>confdefs.h <<\EOF
 #define HAVE_GETHOSTNAME_PROTO 1
 EOF
 
 else
-  echo "$as_me:13569: result: no" >&5
+  echo "$as_me:13568: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 rm -f conftest*
 
-echo "$as_me:13574: checking XFce directory structure" >&5
+echo "$as_me:13573: checking XFce directory structure" >&5
 echo $ECHO_N "checking XFce directory structure... $ECHO_C" >&6
 
 # Check whether --with-data-dir or --without-data-dir was given.
@@ -13619,13 +13618,13 @@ else
 fi
 fi;
 
-echo "$as_me:13622: result: ok" >&5
+echo "$as_me:13621: result: ok" >&5
 echo "${ECHO_T}ok" >&6
-echo "$as_me:13624: result: XFCE_DIR set to $XFCE_DIR" >&5
+echo "$as_me:13623: result: XFCE_DIR set to $XFCE_DIR" >&5
 echo "${ECHO_T}XFCE_DIR set to $XFCE_DIR" >&6
-echo "$as_me:13626: result: XFCE_LOCALE_DIR set to $XFCE_LOCALE_DIR" >&5
+echo "$as_me:13625: result: XFCE_LOCALE_DIR set to $XFCE_LOCALE_DIR" >&5
 echo "${ECHO_T}XFCE_LOCALE_DIR set to $XFCE_LOCALE_DIR" >&6
-echo "$as_me:13628: result: XFCE_CONFDIR set to $XFCE_CONFDIR" >&5
+echo "$as_me:13627: result: XFCE_CONFDIR set to $XFCE_CONFDIR" >&5
 echo "${ECHO_T}XFCE_CONFDIR set to $XFCE_CONFDIR" >&6
 
 ac_config_files="$ac_config_files Makefile libs/Makefile xfce/Makefile xfwm/Makefile xftree/Makefile xftree/icons/Makefile xfpager/Makefile xfmouse/Makefile xfrun/Makefile xfbd/Makefile xfclock/Makefile xfsound/Makefile xfgnome/Makefile xfmenu/Makefile xfdiff/Makefile xfdiff/icons/Makefile xfglob/Makefile xfglob/icons/Makefile xfsamba/Makefile xfsamba/icons/Makefile xfumed/Makefile xfumed/icons/Makefile scripts/Makefile intl/Makefile dt/Makefile gdm/Makefile xfce_theme/Makefile cursors/Makefile other/Makefile backdrops/Makefile icons/Makefile palettes/Makefile sounds/Makefile docs/Makefile docs/images/Makefile docs/sgml/Makefile docs/html/Makefile docs/html/stylesheet-images/Makefile textures/Makefile fonts/Makefile po/Makefile.in po/Makefile"
@@ -13708,7 +13707,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:13711: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:13710: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -13887,7 +13886,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:13890: error: ambiguous option: $1
+    { { echo "$as_me:13889: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13906,7 +13905,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:13909: error: unrecognized option: $1
+  -*) { { echo "$as_me:13908: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -13994,7 +13993,7 @@ do
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:13997: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:13996: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -14288,7 +14287,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:14291: creating $ac_file" >&5
+    { echo "$as_me:14290: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -14306,7 +14305,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14309: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14308: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14319,7 +14318,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14322: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14321: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14380,7 +14379,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:14383: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:14382: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -14391,7 +14390,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14394: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14393: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14404,7 +14403,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14407: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14406: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14521,7 +14520,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:14524: $ac_file is unchanged" >&5
+      { echo "$as_me:14523: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -14572,11 +14571,11 @@ for ac_file in : $CONFIG_LINKS; do test "x$ac_file" = x: && continue
   ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
   ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
 
-  { echo "$as_me:14575: linking $srcdir/$ac_source to $ac_dest" >&5
+  { echo "$as_me:14574: linking $srcdir/$ac_source to $ac_dest" >&5
 echo "$as_me: linking $srcdir/$ac_source to $ac_dest" >&6;}
 
   if test ! -r $srcdir/$ac_source; then
-    { { echo "$as_me:14579: error: $srcdir/$ac_source: File not found" >&5
+    { { echo "$as_me:14578: error: $srcdir/$ac_source: File not found" >&5
 echo "$as_me: error: $srcdir/$ac_source: File not found" >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -14626,7 +14625,7 @@ done; }
   # Make a symlink if possible; otherwise try a hard link.
   ln -s $ac_rel_source $ac_dest 2>/dev/null ||
     ln $srcdir/$ac_source $ac_dest ||
-    { { echo "$as_me:14629: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
+    { { echo "$as_me:14628: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
 echo "$as_me: error: cannot link $ac_dest to $srcdir/$ac_source" >&2;}
    { (exit 1); exit 1; }; }
 done
