Rebuild autoconf/automake files
(Old svn revision: 582)

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13542,7 +13542,7 @@ echo "${ECHO_T}XFCE_LOCALE_DIR set to $XFCE_LOCALE_DIR" >&6
 echo "$as_me:13542: result: XFCE_CONFDIR set to $XFCE_CONFDIR" >&5
 echo "${ECHO_T}XFCE_CONFDIR set to $XFCE_CONFDIR" >&6
 
-ac_config_files="$ac_config_files Makefile libs/Makefile xfce/Makefile xfwm/Makefile xftree/Makefile xfpager/Makefile xfmouse/Makefile xfrun/Makefile xfbd/Makefile xfclock/Makefile xfsound/Makefile xfgnome/Makefile xfmenu/Makefile xfdiff/Makefile xfglob/Makefile xfsamba/Makefile xfumed/Makefile scripts/Makefile intl/Makefile dt/Makefile gdm/Makefile xfce_theme/Makefile po/Makefile.in po/Makefile other/Makefile.in other/Makefile backdrops/Makefile.in backdrops/Makefile icons/Makefile.in icons/Makefile palettes/Makefile.in palettes/Makefile sounds/Makefile.in sounds/Makefile docs/Makefile.in docs/Makefile textures/Makefile.in textures/Makefile cursors/Makefile.in cursors/Makefile fonts/Makefile.in fonts/Makefile"
+ac_config_files="$ac_config_files Makefile libs/Makefile xfce/Makefile xfwm/Makefile xftree/Makefile xfpager/Makefile xfmouse/Makefile xfrun/Makefile xfbd/Makefile xfclock/Makefile xfsound/Makefile xfgnome/Makefile xfmenu/Makefile xfdiff/Makefile xfglob/Makefile xfsamba/Makefile xfumed/Makefile scripts/Makefile intl/Makefile dt/Makefile gdm/Makefile xfce_theme/Makefile cursors/Makefile other/Makefile backdrops/Makefile icons/Makefile palettes/Makefile sounds/Makefile docs/Makefile docs/images/Makefile docs/html/Makefile docs/html/stylesheet-images/Makefile textures/Makefile fonts/Makefile po/Makefile.in po/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -13884,31 +13884,25 @@ do
   "dt/Makefile" ) CONFIG_FILES="$CONFIG_FILES dt/Makefile" ;;
   "gdm/Makefile" ) CONFIG_FILES="$CONFIG_FILES gdm/Makefile" ;;
   "xfce_theme/Makefile" ) CONFIG_FILES="$CONFIG_FILES xfce_theme/Makefile" ;;
+  "cursors/Makefile" ) CONFIG_FILES="$CONFIG_FILES cursors/Makefile" ;;
+  "other/Makefile" ) CONFIG_FILES="$CONFIG_FILES other/Makefile" ;;
+  "backdrops/Makefile" ) CONFIG_FILES="$CONFIG_FILES backdrops/Makefile" ;;
+  "icons/Makefile" ) CONFIG_FILES="$CONFIG_FILES icons/Makefile" ;;
+  "palettes/Makefile" ) CONFIG_FILES="$CONFIG_FILES palettes/Makefile" ;;
+  "sounds/Makefile" ) CONFIG_FILES="$CONFIG_FILES sounds/Makefile" ;;
+  "docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/Makefile" ;;
+  "docs/images/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/images/Makefile" ;;
+  "docs/html/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/html/Makefile" ;;
+  "docs/html/stylesheet-images/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/html/stylesheet-images/Makefile" ;;
+  "textures/Makefile" ) CONFIG_FILES="$CONFIG_FILES textures/Makefile" ;;
+  "fonts/Makefile" ) CONFIG_FILES="$CONFIG_FILES fonts/Makefile" ;;
   "po/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES po/Makefile.in" ;;
   "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
-  "other/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES other/Makefile.in" ;;
-  "other/Makefile" ) CONFIG_FILES="$CONFIG_FILES other/Makefile" ;;
-  "backdrops/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES backdrops/Makefile.in" ;;
-  "backdrops/Makefile" ) CONFIG_FILES="$CONFIG_FILES backdrops/Makefile" ;;
-  "icons/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES icons/Makefile.in" ;;
-  "icons/Makefile" ) CONFIG_FILES="$CONFIG_FILES icons/Makefile" ;;
-  "palettes/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES palettes/Makefile.in" ;;
-  "palettes/Makefile" ) CONFIG_FILES="$CONFIG_FILES palettes/Makefile" ;;
-  "sounds/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES sounds/Makefile.in" ;;
-  "sounds/Makefile" ) CONFIG_FILES="$CONFIG_FILES sounds/Makefile" ;;
-  "docs/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES docs/Makefile.in" ;;
-  "docs/Makefile" ) CONFIG_FILES="$CONFIG_FILES docs/Makefile" ;;
-  "textures/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES textures/Makefile.in" ;;
-  "textures/Makefile" ) CONFIG_FILES="$CONFIG_FILES textures/Makefile" ;;
-  "cursors/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES cursors/Makefile.in" ;;
-  "cursors/Makefile" ) CONFIG_FILES="$CONFIG_FILES cursors/Makefile" ;;
-  "fonts/Makefile.in" ) CONFIG_FILES="$CONFIG_FILES fonts/Makefile.in" ;;
-  "fonts/Makefile" ) CONFIG_FILES="$CONFIG_FILES fonts/Makefile" ;;
   "$ac_config_links_1" ) CONFIG_LINKS="$CONFIG_LINKS $ac_config_links_1" ;;
   "default-1" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-1" ;;
   "default-2" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default-2" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h" ;;
-  *) { { echo "$as_me:13911: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:13905: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -14199,7 +14193,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:14202: creating $ac_file" >&5
+    { echo "$as_me:14196: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -14217,7 +14211,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14220: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14214: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14230,7 +14224,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14233: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14227: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14291,7 +14285,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:14294: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:14288: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -14302,7 +14296,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:14305: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:14299: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -14315,7 +14309,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:14318: error: cannot find input file: $f" >&5
+           { { echo "$as_me:14312: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -14432,7 +14426,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:14435: $ac_file is unchanged" >&5
+      { echo "$as_me:14429: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
@@ -14483,11 +14477,11 @@ for ac_file in : $CONFIG_LINKS; do test "x$ac_file" = x: && continue
   ac_dest=`echo "$ac_file" | sed 's,:.*,,'`
   ac_source=`echo "$ac_file" | sed 's,[^:]*:,,'`
 
-  { echo "$as_me:14486: linking $srcdir/$ac_source to $ac_dest" >&5
+  { echo "$as_me:14480: linking $srcdir/$ac_source to $ac_dest" >&5
 echo "$as_me: linking $srcdir/$ac_source to $ac_dest" >&6;}
 
   if test ! -r $srcdir/$ac_source; then
-    { { echo "$as_me:14490: error: $srcdir/$ac_source: File not found" >&5
+    { { echo "$as_me:14484: error: $srcdir/$ac_source: File not found" >&5
 echo "$as_me: error: $srcdir/$ac_source: File not found" >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -14537,7 +14531,7 @@ done; }
   # Make a symlink if possible; otherwise try a hard link.
   ln -s $ac_rel_source $ac_dest 2>/dev/null ||
     ln $srcdir/$ac_source $ac_dest ||
-    { { echo "$as_me:14540: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
+    { { echo "$as_me:14534: error: cannot link $ac_dest to $srcdir/$ac_source" >&5
 echo "$as_me: error: cannot link $ac_dest to $srcdir/$ac_source" >&2;}
    { (exit 1); exit 1; }; }
 done
